// Vendored disposable / throwaway email domains (T7, spec G: abuse control).
//
// SOURCE: hand-curated from the widely-mirrored disposable-email-domains lists
// (github.com/disposable-email-domains/disposable-email-domains and
// github.com/ivolo/disposable-email-domains), narrowed to the highest-traffic,
// unambiguous throwaway providers. Deliberately CONSERVATIVE: the invite-code gate is
// the stronger control, so this list favors ZERO false positives over completeness —
// a real user's permanent address must never be blocked. It is fine for a determined
// abuser to slip a domain through; that is what the invite gate is for.
//
// UPDATE PROCEDURE: add lowercase REGISTRABLE domains only (e.g. "mailinator.com", not
// "sub.mailinator.com" — subdomain matching is handled by lib/emailGuard.ts). Keep the
// set alphabetized. Matching is an O(1) Set lookup over each domain suffix; do not add
// regexes or wildcards here. When in doubt, leave it out.
export const DISPOSABLE_EMAIL_DOMAINS: ReadonlySet<string> = new Set([
  "0-mail.com",
  "10minutemail.com",
  "10minutemail.net",
  "20minutemail.com",
  "33mail.com",
  "throwawaymail.com",
  "getairmail.com",
  "guerrillamail.biz",
  "guerrillamail.com",
  "guerrillamail.de",
  "guerrillamail.info",
  "guerrillamail.net",
  "guerrillamail.org",
  "guerrillamailblock.com",
  "sharklasers.com",
  "grr.la",
  "spam4.me",
  "mailinator.com",
  "mailinator.net",
  "mailinator2.com",
  "mailnesia.com",
  "maildrop.cc",
  "mailcatch.com",
  "mintemail.com",
  "mohmal.com",
  "moakt.com",
  "temp-mail.org",
  "temp-mail.io",
  "tempmail.com",
  "tempmailo.com",
  "tempr.email",
  "tmail.ws",
  "tmails.net",
  "dispostable.com",
  "fakeinbox.com",
  "fakemailgenerator.com",
  "trashmail.com",
  "trashmail.de",
  "trash-mail.com",
  "yopmail.com",
  "yopmail.net",
  "yopmail.fr",
  "cool.fr.nf",
  "jetable.org",
  "nada.email",
  "getnada.com",
  "emailondeck.com",
  "throwawaymail.net",
  "mailexpire.com",
  "mytemp.email",
  "mailtemp.net",
  "burnermail.io",
  "spambog.com",
  "spamgourmet.com",
  "discard.email",
  "discardmail.com",
  "einrot.com",
  "wegwerfmail.de",
  "wegwerfmail.net",
  "harakirimail.com",
  "inboxbear.com",
  "inboxkitten.com",
  "tempinbox.com",
  "vomoto.com",
  "mail-temp.com",
  "1secmail.com",
  "1secmail.org",
  "1secmail.net",
  "emltmp.com",
  "luxusmail.org",
  "mailpoof.com",
  "muellmail.com",
  "rteet.com",
  "byom.de",
]);
