import type { Metadata } from "next";
import { SupportLink } from "@/components/SupportLink";
import { ReadingShell } from "@/components/ui/SystemStates";

// NOTE: Content-reviewed against the codebase on 2026-07-05 (billing, refund, and
// export/deletion claims verified in code) and shipped on the operator's decision for
// the invite-only beta. It has NOT been reviewed by a lawyer, is not legal advice, and
// does not substitute for review by counsel before a broader public launch.
export const metadata: Metadata = { title: "Terms of Service · Rolefit" };

export default function TermsPage() {
  return (
    <ReadingShell title="Terms of Service" meta="Last updated 2026-07-05">

        <p>
          These terms govern your use of Rolefit (&ldquo;the Service&rdquo;), a job-search
          assistant that reviews public job postings against your profile and helps you
          prepare applications. Rolefit is operated by Andrew Malvani (&ldquo;we,&rdquo;
          &ldquo;us&rdquo;). By creating an account you agree to these terms and to our{" "}
          <a href="/privacy">Privacy Policy</a>.
        </p>

        <h2>Accounts</h2>
        <p>
          You must be at least 18 years old to use the Service. You must provide accurate
          information, keep your credentials secure, and be responsible for activity under
          your account. Accounts are currently invite-only. You must use a permanent email
          address.
        </p>

        <h2>Your content</h2>
        <p>
          You retain ownership of the résumé text, instructions, and profile details you
          provide. You grant us a limited license to process that content solely to operate
          the Service — reviewing jobs for you and generating tailored résumés and cover
          letters. To do this we send your résumé and instructions to third-party AI model
          providers; see the <a href="/privacy">Privacy Policy</a> for the
          full list of processors.
        </p>

        <h2>Acceptable use</h2>
        <p>
          Do not misuse the Service: no automated scraping of other users&rsquo; data, no
          attempts to bypass tenant isolation or usage caps, no uploading of content you do
          not have the right to share, and no unlawful activity. We may suspend accounts that
          abuse the Service or its cost controls.
        </p>

        <h2>Subscriptions &amp; billing</h2>
        <p>
          Paid plans are billed monthly, in advance, through Stripe. Your plan sets a
          per-day review budget and a monthly generation allowance. You can change or cancel
          your plan at any time from the billing page; cancellation takes effect at the end
          of the current billing period. Partial periods are not automatically prorated or
          refunded, but if something went wrong, contact us — we review refund requests in
          good faith and can issue refunds through Stripe. We do not store your card
          details — Stripe handles all payment data.
        </p>

        <h2>AI-generated output</h2>
        <p>
          Job reviews, tailored résumés, and cover letters are generated by large language
          models and may contain errors. They are suggestions, not guarantees. Review
          everything before you rely on or submit it. We are not responsible for hiring
          outcomes.
        </p>

        <h2>Data export &amp; deletion</h2>
        <p>
          You can export everything we hold about you, and permanently delete your account,
          from your <a href="/profile">profile page</a>. Deletion is
          irreversible: it removes your profile, reviews, generated packages, and archived
          résumé files, and cancels any active subscription.
        </p>

        <h2>Disclaimers &amp; liability</h2>
        <p>
          The Service is provided &ldquo;as is,&rdquo; without warranties of any kind. To the
          maximum extent permitted by law, we are not liable for indirect or consequential
          damages, and our total liability is limited to the amount you paid us in the
          preceding three months.
        </p>

        <h2>Changes</h2>
        <p>
          We may update these terms; material changes will be reflected by the date above.
          Continued use after a change means you accept the updated terms.
        </p>

        <h2>Contact</h2>
        <p>
          Questions about these terms?{" "}
          <SupportLink label="Contact support" subject="Terms of Service question" /> or see
          our <a href="/privacy">Privacy Policy</a>.
        </p>
    </ReadingShell>
  );
}
