import type { Metadata } from "next";
import { SupportLink } from "@/components/SupportLink";

// NOTE: This copy is a good-faith starting point and MUST be reviewed by a lawyer
// before public launch (see the commit message). It is not legal advice.
export const metadata: Metadata = { title: "Terms of Service · Rolefit" };

const pageStyle: React.CSSProperties = {
  minHeight: "100vh", background: "var(--bg-page)", color: "var(--text-primary)", padding: "48px 20px 72px",
};
const cardStyle: React.CSSProperties = {
  maxWidth: "760px", margin: "0 auto", background: "var(--bg-surface)", border: "1px solid var(--border)",
  borderRadius: "18px", boxShadow: "0 12px 40px rgba(15,22,35,.08)", padding: "34px 38px 40px",
};
const h1Style: React.CSSProperties = {
  margin: "0 0 4px", fontSize: "24px", fontWeight: 800, letterSpacing: "-.4px", color: "var(--text-primary)",
};
const metaStyle: React.CSSProperties = { fontSize: "12.5px", color: "var(--text-muted)", marginBottom: "24px" };
const h2Style: React.CSSProperties = {
  fontSize: "15px", fontWeight: 800, color: "var(--text-primary)", margin: "26px 0 8px",
};
const pStyle: React.CSSProperties = {
  fontSize: "13.5px", lineHeight: 1.7, color: "var(--text-primary)", margin: "0 0 10px",
};
const linkStyle: React.CSSProperties = { color: "var(--accent)", fontWeight: 600, textDecoration: "none" };

export default function TermsPage() {
  return (
    <main style={pageStyle}>
      <div style={cardStyle}>
        <h1 style={h1Style}>Terms of Service</h1>
        <div style={metaStyle}>Last updated 2026-07-04</div>

        <p style={pStyle}>
          These terms govern your use of Rolefit (&ldquo;the Service&rdquo;), a job-search
          assistant that reviews public job postings against your profile and helps you
          prepare applications. By creating an account you agree to these terms and to our{" "}
          <a href="/privacy" style={linkStyle}>Privacy Policy</a>.
        </p>

        <h2 style={h2Style}>Accounts</h2>
        <p style={pStyle}>
          You must provide accurate information, keep your credentials secure, and be
          responsible for activity under your account. Accounts are currently invite-only.
          You must use a permanent email address.
        </p>

        <h2 style={h2Style}>Your content</h2>
        <p style={pStyle}>
          You retain ownership of the résumé text, instructions, and profile details you
          provide. You grant us a limited license to process that content solely to operate
          the Service — reviewing jobs for you and generating tailored résumés and cover
          letters. To do this we send your résumé and instructions to third-party AI model
          providers; see the <a href="/privacy" style={linkStyle}>Privacy Policy</a> for the
          full list of processors.
        </p>

        <h2 style={h2Style}>Acceptable use</h2>
        <p style={pStyle}>
          Do not misuse the Service: no automated scraping of other users&rsquo; data, no
          attempts to bypass tenant isolation or usage caps, no uploading of content you do
          not have the right to share, and no unlawful activity. We may suspend accounts that
          abuse the Service or its cost controls.
        </p>

        <h2 style={h2Style}>Subscriptions &amp; billing</h2>
        <p style={pStyle}>
          Paid plans are billed monthly through Stripe. Your plan sets a per-day review
          budget and a monthly generation allowance. You can change or cancel your plan at
          any time from the billing page; cancellation takes effect at the end of the current
          period, and downgrades keep your current benefits until then. We do not store your
          card details — Stripe handles all payment data.
        </p>

        <h2 style={h2Style}>AI-generated output</h2>
        <p style={pStyle}>
          Job reviews, tailored résumés, and cover letters are generated by large language
          models and may contain errors. They are suggestions, not guarantees. Review
          everything before you rely on or submit it. We are not responsible for hiring
          outcomes.
        </p>

        <h2 style={h2Style}>Data export &amp; deletion</h2>
        <p style={pStyle}>
          You can export everything we hold about you, and permanently delete your account,
          from your <a href="/profile" style={linkStyle}>profile page</a>. Deletion is
          irreversible: it removes your profile, reviews, generated packages, and archived
          résumé files, and cancels any active subscription.
        </p>

        <h2 style={h2Style}>Disclaimers &amp; liability</h2>
        <p style={pStyle}>
          The Service is provided &ldquo;as is,&rdquo; without warranties of any kind. To the
          maximum extent permitted by law, we are not liable for indirect or consequential
          damages, and our total liability is limited to the amount you paid us in the
          preceding three months.
        </p>

        <h2 style={h2Style}>Changes</h2>
        <p style={pStyle}>
          We may update these terms; material changes will be reflected by the date above.
          Continued use after a change means you accept the updated terms.
        </p>

        <h2 style={h2Style}>Contact</h2>
        <p style={pStyle}>
          Questions about these terms?{" "}
          <SupportLink label="Contact support" subject="Terms of Service question" /> or see
          our <a href="/privacy" style={linkStyle}>Privacy Policy</a>.
        </p>
      </div>
    </main>
  );
}
